spring:
  application:
    name: hackathon
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hakathon
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  server:
    port: 8080
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
  springdoc:
    swagger-ui:
      path: /swagger-ui.html
